version: '3.8'

services:
  my-jenkins:
    image: my-jenkins
    container_name: my-jenkins
    restart: on-failure
    user: root  # 🚨 Crucial: Le da permisos a Jenkins para usar el teléfono (socket)
    environment:
      - JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CSP="default-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
    volumes:
      - jenkins-data:/var/jenkins_home
      # 🔌 Conectamos el cable telefónico al Docker de tu computadora real:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000:8080"
      - "50000:50000"
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-data: