name: CI

# Define cuándo se ejecutará este flujo de trabajo
on:
  # Se ejecuta automáticamente cada vez que se sube código a la rama principal (main)
  push:
    branches:
      - main
  
  # Permite disparar el flujo de trabajo manualmente desde la interfaz web de GitHub
  workflow_dispatch:

jobs:
  # --- TRABAJO 1: PRUEBAS DEL BACKEND ---
  unit-tests-backend:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar/Descargar el código del repositorio en el contenedor virtual
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      # Paso 2: Instalar y configurar Go con sistema de caché para optimizar velocidad
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          # Ruta al archivo de dependencias para acelerar futuras ejecuciones usando la caché
          cache-dependency-path: bugtracker-backend/go.sum

      # Paso 3: Instalar la utilidad para convertir los tests de Go a formato JUnit (XML)
      - name: Install go-junit-report
        run: go install github.com/jstemmer/go-junit-report/v2@latest

      # Paso 4: Ejecutar las pruebas unitarias y redirigir la salida hacia el archivo XML
      - name: Execute Backend Unit Tests
        working-directory: ./bugtracker-backend
        run: |

          go test -json -coverprofile=coverage.out -covermode=atomic ./...
          go tool cover -func=coverage.out > coverage.text

          echo "## Go Test Code Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat coverage.text >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

          go test -v ./... 2>&1 | go-junit-report > test-results.xml          

      # Paso 5: Publicar los resultados de las pruebas del Backend
      - name: Publish Backend Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Backend Unit Tests Report
          path: bugtracker-backend/test-results.xml
          reporter: jest-junit


# --- TRABAJO 2: PRUEBAS DEL FRONTEND ---
  unit-tests-frontend:
    # Esta línea fuerza a que este trabajo espere a que el backend termine con éxito
    needs:   unit-tests-backend
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Clonar el código en este nuevo contenedor
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      # Paso 2: Instalar Node.js v20 y configurar la caché para npm
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: "lts/*"
          cache: "npm"
          # Ruta al archivo de bloqueo para verificar cambios y optimizar la caché
          cache-dependency-path: bugtracker-frontend/package-lock.json

      # Paso 3: Instalar dependencias limpias, ejecutar pruebas y capturar la salida de consola
      - name: Execute Frontend Unit Tests
        working-directory: ./bugtracker-frontend
        run: |
         npm ci
         npm test | tee full_output.txt

      # Paso 4: Escribir el reporte de cobertura del Frontend en el panel de resumen
      - name: Write Frontend Coverage to Job Summary
        working-directory: ./bugtracker-frontend
        if: always()
        run: |
          echo "## Frontend Test Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat full_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      # Paso 5: Publicar los resultados de las pruebas del Frontend
      - name: Publish Frontend Test Results
        uses: dorny/test-reporter@v1
        # if: always() asegura que este paso se ejecute incluso si el paso "npm test" falla.
        if: always()
        with:
          name: Frontend Unit Tests Report
          path: bugtracker-frontend/test-results.xml
          reporter: jest-junit  